NebraLtd/hm-diag

- Dockerfile
> Armv5 raspbian

- Dockerfile
> Revert "Change nginx location"

- Dockerfile
> Revert "Python3 json issue"

- Dockerfile
> Revert "Armv5 raspbian"

- diagnostics-program/html_generator.py
open helium explorer link in new tab
> open helium explorer link in new tab

- diagnostics-program/main.py
Fix percentage display
Closes: #69 
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
> Fix percentage display

- Dockerfile
- default.conf
- diagnostics-program/html_generator.py
- diagnostics-program/main.py
- diagnostics-program/utils.py
> fix path, remove unavailable key, edit dockerfile, edit nginx conf

- README.md
**Why**
As a developer without any prior knowledge, I should be able to get started without reading any code.
**How**
Explain how to access the web interface and how to deploy to a development device.
> docs: add beginner instructions to README

- hw_diag/templates/diagnostics_page.html
- hw_diag/tests/test_should_display_lte.py
- hw_diag/utilities/hardware.py
- hw_diag/views/diagnostics.py
- requirements.txt
Closes: https://github.com/NebraLtd/hm-diag/issues/101
Closes: #105 
Only display LTE status for variants which are LTE capable.
> Conditionally display LTE based on variant

- README.md
**Why**
Make documentation more accurate for future reference
**How**
- reorganise in same alphabetical order that JSON outputs in
- add missing parameters from JSON
- clarify some definitions
**References**
> docs: reorganise and add missing

- hw_diag/tests/test_get_public_keys.py
- hw_diag/utilities/miner.py
Hotfix for new layout of `public_keys` file
> Fixes new layout of public_key file

- hw_diag/tests/test_get_public_keys.py
- hw_diag/tests/test_views_diagnostics.py
- hw_diag/views/diagnostics.py
- setup.py
**Why**
Tidy up repo
**How**
- add description and email
- fix some flake8 stuff
**References**
#118
> fix: add some data and add some flake fixes

- hw_diag/templates/diagnostics_page.html
**Why**
There are some parts of the diagnostics page that required some tweaking to improve readability, such as missing Ethernet or WiFi MAC.
**How**
Improves handling and reworks wording a bit to improve readability.
**References**
Closes https://github.com/NebraLtd/hm-diag/issues/126
> Minor cosmetic changes

- hw_diag/templates/diagnostics_page.html
remove typo
**Why**
**How**
**References**
> remove typo

- hw_diag/templates/diagnostics_page.html
add theme colour
**Why**
Make things prettier on mobile
**How**
`<meta name="theme-color" content="#03a9f4">`
**References**
> meta: add theme colour

- .github/workflows/compile-docker.yml
- .github/workflows/rust-compiler.yml
- Dockerfile
- hw_diag/utilities/miner.py
- hw_diag/views/diagnostics.py
- requirements.txt
* Speeds up manufacturing
* Removes duplicate installed python dependencies
* Exposes WiFi MAC to `initFile.txt`
References:
* Closes https://github.com/NebraLtd/hm-diag/issues/135
* Refs https://github.com/NebraLtd/hm-diag/issues/137
> Manufacturing tweaks

- .github/workflows/compile-docker.yml
> Fixes dependency

- hw_diag/utilities/hardware.py
- hw_diag/views/diagnostics.py
**Why**
Add more tested modems
**How**
Add USB identifiers
**References**
Relates to #145 and #88 
https://github.com/NebraLtd/Helium-Guides/blob/main/docs/outdoor-hotspot/lte-config.md
> Add more modems

- hw_diag/views/diagnostics.py
- requirements.txt
**Why**
bump sensecap, rak, helium hotspot details
**How**
fix up helium-hardware-definitions and pull in the new versions
**References**
https://github.com/NebraLtd/helium-hardware-definitions/releases/tag/v0.1.6a3
> bump sensecap, rak, helium hotspot details

- .github/workflows/python-tests.yml
- hw_diag/tests/test_get_miner_diag.py
**Why**
Fixes Flake8 related issues and converts Flake8 in CI to be enforcing.
**How**
**References**
> Fix Flake8 Errors & Enable Enforcing Flake8

- GCS_DIAGNOSTICS_SHIPPING.md
- bigquery/bq_funcs.js
- bigquery/bq_schema.json
- hw_diag/tasks.py
- hw_diag/tests/test_gcs_shipper.py
- hw_diag/utilities/gcs_shipper.py
Pushes miners config each time the diagnostics task is run  so we can query miner status over time with Big Query.
> Upload diagnostics to GCS periodically

- hw_diag/app.py
- hw_diag/tasks.py
- hw_diag/tests/test_gcs_shipper.py
- hw_diag/utilities/gcs_shipper.py
**Why**
**How**
**References**
> Ship diagnostics hourly

- GCS_DIAGNOSTICS_SHIPPING.md
- bigquery/bq_funcs.js
- bigquery/import_script.py
- bigquery/requirements.txt
Not ready for merge yet, required docs update...
> Add import function script for BigQuery

- hw_diag/utilities/hardware.py
- requirements.txt
**Why**
Add support for RockPi which uses i2c-7
**How**
Add i2c-7 to the check
**References**
#237
> fix: support RockPi with i2c-7

- .github/pull_request_template.md
**Why**
We are setting up a new PR template 
**How**
Applied new PR template to PR file
**References**
[Issue 23](https://github.com/NebraLtd/product-management/issues/23)
> feat: new PR template

- hw_diag/app.py
Provision_key was never getting called because if was in main() function while gunicorn via docker was calling the get_app function.
**Issue**
No new miners passing manufacturing.
- Link: https://github.com/NebraLtd/hm-diag/issues/264
> provision_key was never getting called 

- Edit column names in bigquery table.md
- bigquery/bq_schema.json
- bigquery/import_script.py
- hw_diag/tests/test_gcs_shipper.py
- hw_diag/utilities/gcs_shipper.py
**Issue**
Closes #220 
**Checklist**
> Prepare for bigquery schema change

- requirements.txt
**Issue**
- Link: N/A
- Summary: bump pyhelper module to latest
**How**
Bump pyhelper module to latest version.
Brings in changes to i2c bus decision logic.
**References**
Relates to https://github.com/NebraLtd/hm-pyhelper/pull/84
**Checklist**
> feat: bump pyhelper module

- hw_diag/templates/diagnostics_page.html
- hw_diag/views/diagnostics.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> add date into template

- hw_diag/app.py
- hw_diag/utilities/download.py
- hw_diag/utilities/quectel.py
* added modem ports to diagnostic container
**133**
- Link: https://github.com/NebraLtd/hm-diag/issues/133
- Summary: qfirehose needs these ports to flash the firmware
**How**
**References**
**Checklist**
> feat: add EG25G firmware and flashing tool (#133)

- hw_diag/app.py
Disable Scheduler API as we don't need it.
Refs https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1649936533564709
> Disables APScheduler API

- requirements.txt
**Issue**
NebraLtd/helium-miner-software#465
**Checklist**
> Bumped hm-pyhelper to fix cotx I2C addr issue

- .gitignore
- hw_diag/app.py
- hw_diag/tests/test_balena_supervisor.py
- hw_diag/tests/test_network_watchdog.py
- hw_diag/utilities/balena_supervisor.py
- hw_diag/utilities/dbus_proxy/dbus_ids.py
- hw_diag/utilities/dbus_proxy/network_manager.py
- hw_diag/utilities/network_watchdog.py
**Issue**
- Link: https://github.com/nebraltd/hm-diag/issues/343
- Summary:
To prevent the dropping off the network in hotspots, add network watchdog.
**How**
**References**
**Checklist**
> Introduce a network watchdog

- hw_diag/templates/diagnostics_page_light_miner.html
* update light miner html to include alert message for light migration
**[Issue](https://github.com/NebraLtd/hm-diag/issues/411)**
- Link: https://github.com/NebraLtd/hm-diag/issues/411
- Summary: include a banner alert for light miner migration
**How**
**References**
**Checklist**
> feat: Messaging for disabled blockchain sync #411

- bigquery/events_schema.json
- hw_diag/app.py
- hw_diag/tests/test_event_streamer.py
- hw_diag/utilities/event_streamer.py
- hw_diag/utilities/events_bq_data_model.py
- hw_diag/utilities/network_watchdog.py
* added heart beat event
* included network state in every event
**[Issue](https://github.com/NebraLtd/hm-diag/issues/395)**
- Link: https://github.com/NebraLtd/hm-diag/issues/395
- Summary: added 1 hour repeating heartbeat.
**How**
**References**
**Checklist**
> feat: Upload watchdog events #395

- hw_diag/app.py
* send diagnostics at interval scheduling with jitter.
**[Issue](https://github.com/NebraLtd/hm-diag/issues/426)**
- Link: https://github.com/NebraLtd/hm-diag/issues/426
- Summary:
**How**
**References**
**Checklist**
> feat: Random Upload Intervals of diagnostics#426

- hw_diag/app.py
* emit heartbeat every 24 hours.
**https://github.com/NebraLtd/product-management/issues/167**
- Link: https://github.com/NebraLtd/product-management/issues/167
- Summary:
**How**
**References**
**Checklist**
> fix: Investigate spike in costs #167

- requirements.txt
> hm-pyhelper version bump to include key generation backup logic for key provisioning

- hw_diag/templates/diagnostics_page_light_miner.html
**Issue**
- Link: #398 
- Summary: clarify radio false when no location assert
**How**
clarify radio false when no location assert
**References**
Closes: #398
**Checklist**
> feat: clarify radio false when no location assert

- hw_diag/templates/device_configuration.html
- hw_diag/templates/template.html
Resolves - https://github.com/NebraLtd/hm-diag/issues/453
> Fix naming inconsistency on Device Configuration buttons / page.

- hw_diag/views/diagnostics.py
Fixes https://github.com/NebraLtd/hm-diag/issues/452
> Fix JSON Auth

- hw_diag/templates/password_change_form.html
- hw_diag/tests/test_auth.py
- hw_diag/utilities/auth.py
- hw_diag/views/auth.py
> Bug: Fix padding on password reset error text, fix spelling error, use colour to denote success / error.

- hw_diag/templates/login_form.html
- hw_diag/utilities/auth.py
> Use WiFi MAC for default password if Ethernet unavailable.

- Dockerfile
- hw_diag/utilities/auth.py
- hw_diag/views/auth.py
- start_admin_session
https://github.com/NebraLtd/hm-diag/issues/464
> Allow support to spawn an admin session via Balena public url feature

- .github/workflows/compile-docker.yml
- Dockerfile
- setenv.sh
- start_diagnostics.sh
**Issue**
#468
Also improved Dockerfile for more efficient layering (combined RUN layers)
**Checklist**
> Added production parameter recognition feature (#468)

- hw_diag/utilities/auth.py
> Fix delay caused by set_hostname at hm-diag boot.

- hw_diag/templates/helium_info.html
**Issue**
- Link:
- Summary:
**How**
**References**
Closes: #388 
Closes: #389
Closes: #326 
Closes: #325 
**Checklist**
> feat: better support for non Nebra miners

- .github/workflows/compile-docker.yml
Add amd64 variant
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add amd64 variant

- MANIFEST.in
- hw_diag/app.py
- hw_diag/templates/template_hyper.html
- hw_diag/templates/ttn_config.html
- hw_diag/templates/upgrade.html
- hw_diag/tests/test_app.py
- hw_diag/utilities/auth.py
- hw_diag/utilities/ttn.py
- hw_diag/views/auth.py
- hw_diag/views/diagnostics.py
- hw_diag/views/myst.py
- hw_diag/views/thingsix.py
- hw_diag/views/ttn.py
- Detects if Balena Open Fleet or Balena Commercial Fleet
- Adds TTN configuration page which saves TTN config in JSON format to Nebra volume
- Should be deployed in conjunction with pktmux changes to support TTN
> FEAT: Detect fleet type + Add TTN Support

- hw_diag/templates/helium_info.html
Fixes issues reported during testnet.
> Fix 500 error on Helium info page when rendering template

- hw_diag/app.py
- hw_diag/utilities/network.py
* added code for handling /var/nebra/in_manufacturing file.
**[Issue](https://github.com/NebraLtd/hm-diag/issues/490)**
- Link: https://github.com/NebraLtd/hm-diag/issues/490
- Summary:
**How**
**References**
**Checklist**
> feat : inject in manufacturing variable#490

- start_diagnostics.sh
* update to recent date.
**[Issue](https://github.com/NebraLtd/hm-diag/issues/492)**
- Link:https://github.com/NebraLtd/hm-diag/issues/492
- Summary:
**How**
**References**
**Checklist**
> fix: fixup to a recent date if it is too old #492

- hw_diag/utilities/balena_migration.py
- hw_diag/utilities/hardware.py
- hw_diag/utilities/system_metrics.py
**[Issue](https://github.com/NebraLtd/hm-diag/issues/496)**
- Link: https://github.com/NebraLtd/hm-diag/issues/496
- Summary:
**How**
**References**
**Checklist**
> fix: Use proc/cpuinfo for hardware serial #496

- hw_diag/utilities/hardware.py
* disregard serial from /proc/cpuinfo if it is all zeros
**[Issue](https://github.com/NebraLtd/hm-diag/issues/496)**
- Link: https://github.com/NebraLtd/hm-diag/issues/496
- Summary:
**How**
**References**
**Checklist**
> Use proc/cpuinfo for hardware serial #496

- hw_diag/templates/login_form.html
Add note about upper case
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: clarify upper case

- .gitignore
- hw_diag/app.py
- hw_diag/constants.py
- hw_diag/tests/test_manufacturing_mode.py
- hw_diag/utilities/manufacturing_mode.py
- hw_diag/utilities/network.py
where ping to hpt ip from a later machine in the routing chain caused device to enter manufacturing mode. Also some minor refactoring and test cases.
Re #518 
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Manufacturing fix

- hw_diag/templates/device_info.html
- hw_diag/templates/template.html
- hw_diag/templates/template_hyper.html
- hw_diag/templates/unauthenticated_template.html
update support url
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: change support url

- MANIFEST.in
- hw_diag/templates/device_configuration.html
- hw_diag/templates/device_info.html
- hw_diag/templates/helium_info.html
- hw_diag/templates/login_form.html
- hw_diag/templates/myst.html
- hw_diag/templates/password_change_form.html
- hw_diag/templates/password_reset.html
- hw_diag/templates/reconfigure_countdown.html
- hw_diag/templates/template_hyper.html
- hw_diag/templates/thix_dashboard.html
- hw_diag/templates/thix_error.html
- hw_diag/templates/thix_onboard.html
- hw_diag/templates/thix_setup.html
- hw_diag/templates/ttn_config.html
- hw_diag/templates/upgrade.html
- hw_diag/views/myst.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add MYST Dashboard

- hw_diag/templates/helium_info.html
- hw_diag/views/diagnostics.py
**Issue**
- Link: #539 
- Summary:
**How**
Fix 500 error on HNT template
**References**
Closes: #539 
**Checklist**
> fix 500 error with HNT template

- hw_diag/utilities/auth.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Check Fleet ID

- hw_diag/utilities/auth.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix commercial

- hw_diag/tasks.py
- hw_diag/templates/helium_info.html
- hw_diag/views/diagnostics.py
**Issue**
- Link: #539 
- Summary:
**How**
**References**
Closes: #539 
Closes: #543 
**Checklist**
> fix: repair 500 on helium page (again)

- hw_diag/utilities/auth.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Cast fleet id to int.

- hw_diag/templates/upgrade.html
yuck
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: small typos and disgusting horrible oxford commas

- requirements.txt
* update pyhelper
**[Issue](https://nebraltd.atlassian.net/browse/NEBD-105) **
- Link:https://nebraltd.atlassian.net/browse/NEBD-105
- Summary:
**How**
**References**
**Checklist**
> fix: add create transaction with grpc #NEBD-105

- MANIFEST.in
- hw_diag/templates/thix_error.html
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add error template to manifest

- hw_diag/utilities/auth.py
add new non frequency specific Nebra fleets
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add new non frequency specific Nebra fleets

- requirements.txt
bump hm-pyhelper to v0.14.9
Closes: #557
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: bump hm-pyhelper

- hw_diag/app.py
- hw_diag/constants.py
- hw_diag/templates/device_info.html
- hw_diag/templates/upgrade.html
- hw_diag/tests/test_dashboard_registration.py
- hw_diag/utilities/dashboard_registration.py
- hw_diag/utilities/diagnostics.py
- hw_diag/utilities/hardware.py
- hw_diag/views/auth.py
- hw_diag/views/diagnostics.py
- start_diagnostics.sh
* automatically register third party devices on startup
* keep the registration state saved in sqlite db
* add buys loop env var that prevents diag startup for debugging
**[Issue](https://nebraltd.atlassian.net/browse/NEBD-2)**
- Link: https://nebraltd.atlassian.net/browse/NEBD-2
- Summary:
**How**
**References**
Closes: #470
Closes: #97
Closes: #371
**Checklist**
> feat: Auto register Third party devices on Dashboard #NEBD-2

- hw_diag/utilities/dashboard_registration.py
* fix boolean casting of string
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: bool check in Auto register Third party devices on Dashboard

- requirements.txt
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Bump hm-pyhelper

- hw_diag/tests/test_dashboard_registration.py
- hw_diag/utilities/dashboard_registration.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: disable checking of local registartion state

- hw_diag/templates/template_hyper.html
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Update Myst branding in the sidebar menu.

- requirements.txt
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Bump hm-pyhelper to 0.14.11

- MANIFEST.in
- hw_diag/app.py
- hw_diag/templates/backup_restore.html
- hw_diag/templates/template_hyper.html
- hw_diag/tests/test_app.py
- hw_diag/utilities/backup/__init__.py
- hw_diag/utilities/backup/base.py
- hw_diag/utilities/backup/myst.py
- hw_diag/utilities/backup/nebra.py
- hw_diag/utilities/backup/thingsix.py
- hw_diag/views/backup_restore.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add backup & restore feature

- hw_diag/utilities/backup/nebra.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Use shell for restore command

- hw_diag/tests/test_backup.py
- hw_diag/utilities/backup/myst.py
- hw_diag/utilities/backup/thingsix.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: handle filenotfound exceptions

- hw_diag/templates/template_hyper.html
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Updated sidenav icons

- hw_diag/templates/template_hyper.html
add dashboard link to sidenav
- claim on dashboard if not subscribed
- view on dashboard if in commercial fleet
Closes: #574
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add dashboard link to side nav

- hw_diag/templates/helium_info.html
- hw_diag/templates/thix_dashboard.html
fix inconsistent naming and layouts
https://app.thingsix.com/gateways/0xacebb1738e06d7466a7317279756ac7af5c18cb466bbc8bc249458e97c6617cc
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> thix: fix inconsistent naming and layouts

- hw_diag/templates/thix_dashboard.html
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Fix borders

- hw_diag/views/auth.py
- hw_diag/views/backup_restore.py
- hw_diag/views/diagnostics.py
- hw_diag/views/myst.py
- hw_diag/views/thingsix.py
- hw_diag/views/ttn.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix deeplink

- hw_diag/utilities/hardware.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix serial check for rockpi

- hw_diag/templates/device_info.html
- hw_diag/templates/helium_info.html
Fix table height mismatches
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix table height mismatches

- hw_diag/static/css/style.css
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Fixed link colour in badge spans

- hw_diag/static/css/style.css
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Added margin right to badge light span

- hw_diag/templates/thix_dashboard.html
- hw_diag/utilities/shell.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add versions

- hw_diag/templates/helium_info.html
- hw_diag/templates/thix_dashboard.html
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Links in badge

- hw_diag/templates/helium_info.html
Show awaiting location assertion for unknown location
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Show awaiting location assertion for unknown location

- hw_diag/templates/device_info.html
Ref https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1689944554483239?thread_ts=1689944554.483239&cid=C024BNQ1Y6T
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> add warning about expired subscription

- hw_diag/app.py
- hw_diag/templates/template_hyper.html
- hw_diag/templates/wingbits.html
- hw_diag/tests/test_app.py
- hw_diag/utilities/sdr.py
- hw_diag/views/wingbits.py
Adds page to configure Wingbits...
- Stores configuration as JSON file in /var/nebra/wingbits.json
- Allows setting config variables via form on page
- Detects presence of RTL283* SDRs and displays status on page
- Upon changing settings restarts device containers
Sample wingbits.json
`{
"node_name": "big-chunky-elephant",
"latitude": 0.0,
"longitude": 0.0
}`
> Add Wingbits Integration

- hw_diag/templates/wingbits.html
- hw_diag/templates/wingbits_graph1090.html
- hw_diag/templates/wingbits_tar1090.html
- hw_diag/views/wingbits.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add TAR1090 and Graphs1090 Frames
