NebraLtd/hm-diag

- .github/CODEOWNERS
- .github/contributing.md
- .github/pull_request_template.md
- .github/workflows/python-tests.yml
- Dockerfile
**Why**
A developer should be presented with a template when opening a PR so that they are prompted to give more detailed information and a set of developers should automatically be assigned to review.
**How**
Added `pull_request_template.md` and `contributing.md` to `.github/`.
The Google Doc referenced in `contributing.md` is currently empty.
Added all developers to CODEOWNERS.
**References**
- [PR template instructions](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
- [CODEOWNERS instructions](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#example-of-a-codeowners-file)
> added PR template, guidelines, and CODEOWNERS

- hw_diag/templates/diagnostics_page.html
Format sync percentage as described in #104 
- If greater than 99.8% consider the miner as synced and display 100%
- Format float as 2 decimal places
- Display 100% for percentages > 100%
Closes: #104
> Format sync percentage as per Issue #104

- hw_diag/views/diagnostics.py
**Why**
make json output a downloadable file
**How**
Add request headers using
`response.headers.set('Content-Disposition', 'attachment;filename=nebra-diag.json')`
**References**
> json: make json downloadable instead of in browser

- hw_diag/tasks.py
- hw_diag/tests/test_get_miner_diag.py
- hw_diag/utilities/hardware.py
- requirements.txt
* Deprecates [helium-hardware-definitions](https://github.com/NebraLtd/helium-hardware-definitions) in favor of [hm-pyhelper](https://github.com/NebraLtd/hm-pyhelper)
* Fixes linting error
* Sort imports
> Deprecates hardware-definition python module

- hw_diag/tasks.py
- hw_diag/utilities/miner.py
- hw_diag/views/diagnostics.py
**Why**
Some ECC chips are being corrupted during manufacturing. There may be a race condition between gwmfr and diag. We want to wait for gwmfr to complete before running diagnostics.
**How**
Write to an empty file (AKA touch) when gwmfr completes successfully. Wait for this file to be present before running diagnostics.
**References**
- Slack convo: https://pisupply.slack.com/archives/C024BNQ1Y6T/p1632912403459500
- gwmfr: https://github.com/NebraLtd/hm-gwmfr/pull/18
- helium-miner-software: https://github.com/NebraLtd/helium-miner-software/pull/155
> feat: do not exec diagnostics if gwmfr running

- Dockerfile
- README.md
- docker-compose.yml
- requirements.txt
- setup.py
**Why**
dbus is no longer used as we are getting the miner data through json rpc after #113 and #153 
**How**
remove all dbus references from container
**References**
#113 
#153 
#149
> remove dbus

- hw_diag/tasks.py
- hw_diag/tests/test_hardware.py
- hw_diag/utilities/hardware.py
**Why**
Should be able to generate diagnostics report even if unable to retrieve public keys.
**How**
Diagnostics return values indicating error when ECC fails instead of causing a terminal error.
**References**
Closes: https://github.com/NebraLtd/hm-diag/issues/194
Related to: https://github.com/NebraLtd/hm-diag/issues/181
> fix: tolerate ECC errors

- README.md
- hw_diag/diagnostics/bt_lte_diagnostic.py
- hw_diag/diagnostics/ecc_diagnostic.py
- hw_diag/diagnostics/env_var_diagnostics.py
- hw_diag/diagnostics/key_diagnostics.py
- hw_diag/diagnostics/lora_diagnostic.py
- hw_diag/diagnostics/mac_diagnostics.py
- hw_diag/diagnostics/pf_diagnostic.py
- hw_diag/diagnostics/rpi_serial_diagnostic.py
- hw_diag/tests/diagnostics/test_bt_lte_diagnostics.py
- hw_diag/tests/diagnostics/test_ecc_diagnostic.py
- hw_diag/tests/diagnostics/test_env_var_diagnostics.py
- hw_diag/tests/diagnostics/test_key_diagnostics.py
- hw_diag/tests/diagnostics/test_lora_diagnostic.py
- hw_diag/tests/diagnostics/test_mac_diagnostics.py
- hw_diag/tests/diagnostics/test_pf_diagnostic.py
- hw_diag/tests/diagnostics/test_rpi_serial_diagnostic.py
- hw_diag/views/diagnostics.py
- requirements.txt
- setup.py
- test-requirements.txt
**Why**
The initFile should always return something, even if the miner is not fully operational. 
**How**
Created DiagnosticsReport and Diagnostic concepts for each test we do on the miner.
Each Diagnostic must add a value to the report and cannot cause the report to fail.
The [tests](https://github.com/NebraLtd/hm-diag/pull/201/files#diff-b4c69b275920e57eaa26df2f0192bfc5ab6201d3a1e3583ee590ff3509540963R46) are helpful for understanding what the final output looks like.
**Next steps**
- Add more helpful error messages. Eg still swallowing some info when keys fail
- Update Hotspot-Production-Tool according to this logic
- Move DiagnosticsReport and Diagnostic to hm-pyhelper.
- Remove/update methods in hm-pyhelper that accept `diagnostics` as a parameter.
- Update `perform_hw_diagnostics` …
> refactor initFile and prevent 500s

- hw_diag/diagnostics/ecc_diagnostic.py
- hw_diag/diagnostics/key_diagnostics.py
- hw_diag/utilities/shell.py
@posterzh, I don't mean to step on your toes, but wanted to get some thoughts on this approach. More work is needed on the hm-pyhelper side, even if we do decide to use this approach.
**Why**
ECC access sometimes fails. We suspect it might be because of concurrent access. This PR attempts to prevent concurrent access to the ECC.
**How**
Added LockSingleton to easily instantiate a new instance of a singleton
that is a wrapper around a threading.Lock. Use this singleton lock
whenever the ECC is accessed.
TODO:
- Move LockSingleton to hm-pyhelper
- Update hm-pythelper ecc methods to accept a lock as an optional
parameter. Acquire lock before using ECC, then release when done.
**References**
After completion, determine if this does close any of the below issues.
- …
> feat: no concurrent ecc usage

- hw_diag/views/diagnostics.py
**Why**
There is a [bug in hm_pyhelper](https://github.com/NebraLtd/hm-pyhelper/pull/61) that prevents a subset of the diagnostics from being correctly returned. Although we could use the patched logic, there doesn't seem to be a good reason not to always return the full diagnositcs.
**How**
Don't trim diagnostics before returning.
**References**
~Closes: https://github.com/NebraLtd/hm-diag/issues/167~
Related: https://github.com/NebraLtd/hm-diag/issues/167
Although seemingly unrelated, this is the last hm-diag change needed to finish off this work. It can be closed by a helium-miner-software PR that incorporates these changes.
> feat: return full diagnostics response

- docker-compose.yml
- hw_diag/tasks.py
- hw_diag/templates/diagnostics_page.html
- hw_diag/tests/test_blockchain_helium_height.py
- hw_diag/utilities/blockchain.py
- hw_diag/utilities/miner.py
**Why**
Helium API is timing out, stuck on connecting to API while it's down
**How**
Added a timeout to the request and the dashboard served perfectly after this and displayed the timeout error
**References**
[Issue](https://github.com/NebraLtd/hm-diag/issues/216)
> Fix: Add timeout to request on helium api

- hw_diag/diagnostics/pf_diagnostic.py
- hw_diag/tests/diagnostics/test_pf_diagnostic.py
**Why**
We temporarily want diagnostics to pass without LOR while we work
on startup logic for manufacturing. W0 will be addressed later. We
forgot to make this change as part of earlier work.
**How**
PF only considers ECC, E0, and BT
> fix: diagnostics pass without W0 or LOR

- hw_diag/tasks.py
- hw_diag/templates/diagnostics_page.html
- hw_diag/tests/test_blockchain_helium_height.py
- hw_diag/utilities/blockchain.py
- hw_diag/utilities/miner.py
**Why**
Diagnostics fail entirely if unable to get Helium blockchain height.
**How**
Return -1 if request fails.
It's not clear why the request is failing in the first place.
curl to the same endpoint works from miners that are actively failing.
Tried disabling cache on the request, but no impact.
**References**
Related to: https://github.com/NebraLtd/hm-diag/issues/223
> fix: handle bad response for helium height

- hw_diag/diagnostics/pf_diagnostic.py
- hw_diag/tests/diagnostics/test_pf_diagnostic.py
**Why**
We want to ignore W0 and only consider LOR, BT, E0, and ECC for determining PF.
**How**
Partial revert of: https://github.com/NebraLtd/hm-diag/pull/221/commits/205515f9a5e6aee6954e2f7ab11227b4305f2f17
**References**
- Related to: https://github.com/NebraLtd/hm-diag/issues/222
> fix: LOR should be a factor for PF

- hw_diag/utilities/blockchain.py
**Why**
Helium API was not returning values because of missing headers 
**How**
Added headers specifying the user-agent field and it returned perfectly. Helium API is now happy with our request and returning a proper response
**References**
Closes: #232
> fix: Helium API not returning

- hw_diag/tests/diagnostics/test_version_endpoint.py
- hw_diag/tests/test_views_diagnostics.py
- hw_diag/views/diagnostics.py
Added /version endpoint without actual values to test hm-diag deployment via balena.
This is meant to just test the development flow of adding commit hash in helium-miner-software/docker-compose.yml and deploying to a personal fleet.
> Initial work testing endpoint and balena deployment.

- hw_diag/diagnostics/serial_number_diagnostic.py
- hw_diag/tests/diagnostics/test_serial_number_diagnostic.py
- hw_diag/tests/test_get_serial_number.py
- hw_diag/utilities/hardware.py
**Why**
As a hotspot owner, I want a predictable serial number so that I can onboard.
**How**
Null characters from reading serial number file should not be considered part of serial number.
**References**
- Fixes: Convert RPI to Serial Number hm-diag#219
> fix: strip \x00 from serial number

- Dockerfile
- docker-compose.yml
- hw_diag/tests/test_hardware.py
- hw_diag/utilities/hardware.py
- requirements.txt
**Why**
Detect the BLE and LET devices in better way.
**How**
Get the BLE devices and LTE devices programatically using dbus.
**References**
https://github.com/NebraLtd/hm-diag/issues/96 
https://github.com/NebraLtd/hm-diag/issues/88
>  Better detect BT devices and LTE devices

- requirements.txt
**Why**
Fix rockpi ECC provisioning
**How**
Bump hm-pyhelper version 
**References**
Relates to #253
> feat: bump version number of hm-pyhelper

- hw_diag/templates/diagnostics_page.html
**Why**
As a diagnostics user, I should be able to clearly differentiate miner errors from Helium API errors so that I have a better sense of what is going wrong.
**How**
- Update view template `diagnostics_page.html` to display the both of Miner RPC and Helium API status correctly.
**References**
https://github.com/NebraLtd/hm-diag/issues/235
> fix: display Miner RPC/Helium API availability correctly

- hw_diag/app.py
- hw_diag/templates/diagnostics_page.html
- hw_diag/tests/test_app.py
- hw_diag/tests/test_hardware.py
- hw_diag/utilities/hardware.py
- requirements.txt
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/239
- Summary: Gateway MFR Error causing diagnostics page to not open or create a boot loop on the container.
**How**
Traced back the exception and added handling to the source of the issue. This lets the diagnostics continue gracefully and not raise an exception but instead handle it and display the diagnostics page but with errors displayed on diag view. 
**References**
The screenshot above is what the dashboard looks like with the error handling when ECC fails from the error "Gateway mfr exited with non-zero status"
How to recreate this error locally:
In Balena dashboard set i2c_arm to false and as a result this will trigger the ECC to fail as the bus is inactive. Previously this triggered a boot loop on the …
> Handle gateway mfr exit code exception

- Dockerfile
**Issue**
Closes https://github.com/NebraLtd/hm-diag/issues/273
**How**
In theory, the [healthcheck](https://github.com/NebraLtd/hm-diag/blob/master/Dockerfile#L35-L40) shouldn't really do anything on Balena, since it hasn't been fully implemented. However, as part of the logs in [273](https://github.com/NebraLtd/hm-diag/issues/273) it does indeed seems like they now have been. 
It's still clear if these healthchecks actually do anything, but at least it shouldn't cause any harm to resolve this.
> Adds wget for healthcheck

- hw_diag/app.py
- requirements.txt
**Issue**
Closes #139 
**How**
Set up a Sentry again for the diagnostics project.
Update sentry SDK version.
Test for diag:
**Checklist**
**Repositories in which sentry works, checks:**
> Added configuration for sentry

- hw_diag/templates/diagnostics_page.html
**Issue**
- Link: N/A
- Summary: Change the copyright year range on the diagnostic page from "2020-2021" to "2020-2022".
**How**
- Change 2021 to 2022 in the copyright notice on the bottom of the diag page.
Old:
New:
**References**
N/A
**Checklist**
> Update Copyright Year to 2022

- .gitignore
- hw_diag/diagnostics/env_var_diagnostics.py
- hw_diag/templates/diagnostics_page.html
- hw_diag/tests/diagnostics/test_env_var_diagnostics.py
- hw_diag/tests/test_views_diagnostics.py
- hw_diag/utilities/shell.py
- hw_diag/views/diagnostics.py
Include short git-hash report.
- Link: hm-diag#205 
- Summary:
We needed to include short git hash of main repo (helium-miner-software) for release tracking purposes.
**How**
- The short git hash of main repo is fetched via an environment variable supplied by the main docker container composer (helium-miner-software)
- The hash is propagated via multiple routes (/json, /version, /)
- Short code for Short Git Hash (SGH) has been introduced.
**Checklist**
> feat: Added short Git hash report (hm-diag#205)

- README.md
I forgot to include definition for 'firmware_short_hash' in readme.
**Checklist**
> fixed: Readme file does not include definition for 'firmware_short_hash'

- hw_diag/tests/diagnostics/test_bt_diagnostic.py
- hw_diag/tests/diagnostics/test_ecc_diagnostic.py
- hw_diag/tests/diagnostics/test_env_var_diagnostics.py
- hw_diag/tests/diagnostics/test_key_diagnostics.py
- hw_diag/tests/diagnostics/test_lora_diagnostic.py
- hw_diag/tests/diagnostics/test_lte_diagnostic.py
- hw_diag/tests/diagnostics/test_mac_diagnostics.py
- hw_diag/tests/diagnostics/test_pf_diagnostic.py
- hw_diag/tests/diagnostics/test_serial_number_diagnostic.py
- requirements.txt
**Issue**
Related by [#87](https://github.com/NebraLtd/hm-pyhelper/pull/87#pullrequestreview-840567508)
**How**
Update hm_pyhelper version. Fix unittests.
**Checklist**
> Bump hm_pyhelper version 0.12.2 -> 0.13.1

- Dockerfile
* added modem ports to diagnostic container
**133**
- Link: https://github.com/NebraLtd/hm-diag/issues/133
- Summary: qfirehose needs these ports to flash the firmware
**How**
**References**
**Checklist**
> feat: add EG25G firmware and flashing tool (#133)

- hw_diag/utilities/hardware.py
- requirements.txt
**Issue**
- Link: https://github.com/NebraLtd/hm-pyhelper/pull/84
- Summary: ECC was hard coded
**How**
Instead of hard coding the key storage bus for ECC we will now make it pull in from pyhelper module
**References**
Relates-to: https://github.com/NebraLtd/hm-pyhelper/pull/84
Co-authored-by: radicale <radicale@users.noreply.github.com>
https://github.com/radicale/hm-diag/commit/a3fd21c22dc6230a32518dab347adb3a868e790d
**Checklist**
> feat: pull key storage bus from hardware def

- hw_diag/diagnostics/device_status_diagnostic.py
- hw_diag/tests/diagnostics/test_device_status_diagnostic.py
- hw_diag/utilities/balena_supervisor.py
- hw_diag/views/diagnostics.py
Testing, will convert to real PR when done.
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/335
- Summary: Was previously checking the wrong key in the status payload.
**How**
Use `appState` nstead of the `status` field, as instructed by Balena.
**References**
**Checklist**
> fix: use appState to check device status

- Dockerfile
**[Issue](https://github.com/NebraLtd/helium-miner-software/issues/427)**
- Link: https://github.com/NebraLtd/helium-miner-software/issues/427
- Summary: gateway-rs listens only on local host. Only way to make diag work at this stage is to use host networking. As we are now on host, we have to bind to port 80 for diagnostics to remain working
**How**
- bind diag http server to port 80
**References**
**Checklist**
> fix: Add host networking to hm-miner to access grpc api #427

- hw_diag/diagnostics/gateway_diagnostics.py
- hw_diag/tasks.py
- hw_diag/templates/diagnostics_page.html
- hw_diag/tests/diagnostics/test_add_gateway_txn_diagnostic.py
- hw_diag/tests/test_get_miner_diag.py
- hw_diag/tests/test_views_diagnostics.py
- hw_diag/utilities/miner.py
- hw_diag/views/diagnostics.py
- requirements.txt
**[#321](https://github.com/NebraLtd/hm-diag/issues/321)**
- Link: https://github.com/NebraLtd/hm-diag/issues/321
- Summary: remove local blockchain details and add validator blockchain details.
**How**
- Uses grpc to talk to locally running gateway-rs
- displays validator information in diag page. Shows "disconnected" when it can't connect to validator
**References**
**Checklist**
> Light miner: Diagnostics page should NOT display local blockchain details #321

- hw_diag/templates/diagnostics_page.html
* the validator ip has an embedded link to validator in explorer
**#342**
- Link: https://github.com/NebraLtd/hm-diag/issues/342
- Summary: feedback from support team that one should be able to inspect validator in exporer
**References**
**Checklist**
> Light hotspot: explorer link to connected validator #342

- hw_diag/app.py
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/352
- Summary:
Should not generate sentry errors when `gateway_mfr` is exited with a non-zero status.
**How**
Update the sentry configuration so that error level logging shouldn't mess up the sentry issue and monthly quota.
**References**
**Checklist**
> Update sentry config not to capture error level logging

- hw_diag/tests/diagnostics/test_device_status_diagnostic.py
- hw_diag/tests/test_balena_supervisor.py
- hw_diag/utilities/balena_supervisor.py
Instead of returning a string as a failed device status properly raise exception so the diagnostic fails correctly.
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Raise proper exeception for failed device status

- hw_diag/utilities/balena_supervisor.py
Change log level from error to warning when fetching device status from supervisor api fails.
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Log as warning instead of error if fetching device status fails

- hw_diag/app.py
- hw_diag/tests/test_network_watchdog.py
- hw_diag/utilities/dbus_proxy/dbus_ids.py
- hw_diag/utilities/dbus_proxy/network_manager.py
- hw_diag/utilities/network_watchdog.py
- requirements.txt
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/387
- Summary:
Find out the correct connection status to the local gateway and the internet so that watchdog can work reliably.
**How**
- Use dbus interface to the network manager to get the local gateway IP inside the diagnostics container.
- Use ICMP `ping` method to check the connection status to the local gateway(ex, 192.168.0.1) and public IP(8.8.8.8).
**References**
- https://github.com/NebraLtd/hm-diag/issues/343
- [icmplib](https://pypi.org/project/icmplib/)
**Checklist**
> Use ICMP Ping to local gateway in the watchdog

- hw_diag/tests/test_hardware.py
- hw_diag/utilities/hardware.py
- requirements.txt
**Issue**
- Link: https://github.com/NebraLtd/hm-pyhelper/issues/164
- Summary:
In [detect_ecc](https://github.com/NebraLtd/hm-diag/blob/22a67fad95cd889f5ad45900657afd9a17b09dfb/hw_diag/utilities/hardware.py#L186), `KEY_STORAGE_BUS` field of hardware definitions is referenced to get the i2c bus number of ECC.
In the process of updating `gateway_mfr_rs` to the latest version v0.2.1, `SWARM_KEY_URI` field is added to the hardware definitions to specify the address of the ECC.
We need to refactor `detect_ecc()` method so that either the `SWARM_KEY_URI` or `KEY_STORAGE_BUS` field of the hardware definition can be used for specifying the ECC address.
**How**
In `detect_ecc()` method:
- Try to get the ECC address from `SWARM_KEY_URI` field.
- If above fails, try to get the ECC bus number from …
> Use SWARM_KEY_URI from hardware definitions

- requirements.txt
* use pyhelper version 0.13.32 that includes variant renames and sentry
fixes
**[Issue](https://github.com/NebraLtd/hm-pyhelper/issues/171)**
- Link: https://github.com/NebraLtd/hm-pyhelper/issues/171
- Summary: use pyhelper version with new mappings.
**How**
**References**
**Checklist**
> pull pyhelper-0.13.32 that fixes wlan0 not found sentry error

- hw_diag/app.py
- hw_diag/utilities/sentry.py
- requirements.txt
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/405
- Summary:
Add balena device UUID and balena app name(fleet name) to senty issues as a tag. 
Sentry tag is very convenient for filtering, tag-distribution maps, the frequency and the last time that Sentry has seen a tag.
The primary benefit of the Balena device UUID tag is that it enables further analysis of the Sentry problem on the Balena dashboard.
**How**
- Inside the balena container, get the balena UUID from environment variable `BALENA_DEVICE_UUID` and get balena app name from environment variable `BALENA_APP_NAME`.
- Set sentry tag with balena UUID and balena app name respectively.
**References**
**Checklist**
> Add balena UUID and balena fleet name to sentry tag

- MANIFEST.in
- README.md
- hw_diag/templates/diagnostics_page_light_miner.html
- hw_diag/views/diagnostics.py
**[Issue](https://github.com/NebraLtd/hm-diag/issues/357)**
- Link: https://github.com/NebraLtd/hm-diag/issues/357
- Summary: provide option to hide blockchain infrmation.
**How**
* introduced DISPLAY_MINER_INFO env vairable. It can be set to false to
hide display of miner info on diagnostic page.
* defaults to true
With Miner Info disabled:
With Miner Info enabled:
**References**
**Checklist**
> Consolidate diagnostics page changes for light hotspot activation #357

- bigquery/diag_schema.json
- hw_diag/diagnostics/bigquery_data_model.py
- hw_diag/tests/test_gcs_shipper.py
* start using new schema for diagnostic data
**https://github.com/NebraLtd/hm-diag/issues/404**
- Link: https://github.com/NebraLtd/hm-diag/issues/404
- Summary: use new schema for diag data that makes most fields optional
**How**
**References**
**Checklist**
> feat: Make most fields in big query diagnostic schema as optional #404

- requirements.txt
> Updated hm-pyhelper version to include the ECC key provisioning retry logic.

- hw_diag/app.py
- requirements.txt
Added 5 second sleep before key provisioning. Key provisioning retry interval increased to 15 seconds, bumped up hm-pyhelper version.
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Attempting to fix key provisioning

- hw_diag/app.py
- hw_diag/tests/test_app.py
leaner load for diag app for manufacturing.
> Disable database migrations, auth blueprint and set_hostname at app startup.

- hw_diag/utilities/hardware.py
* catch all possible exceptions while reading /proc/cpuinfo
** Use proc/cpuinfo for hardware serial #496 **
- Link:  Use proc/cpuinfo for hardware serial #496 
- Summary:
**How**
**References**
**Checklist**
> fix: Use proc/cpuinfo for hardware serial #496

- hw_diag/tests/test_hardware.py
- hw_diag/utilities/hardware.py
**Issue**
- Link: #500 
- Summary: grab i2c address from hardware definitions and add override
**How**
- allows us to get the i2c address from the SWARM_KEY_URI in hm-pyhelper instead of hard coding it
- removes legacy KEY_STORAGE_BUS commands and corresponding test cases
- adds SWARM_KEY_URI_OVERRIDE to override the key location using an environment variable
**References**
Closes: #500
**Checklist**
> feat: grab i2c address from hardware definitions and add override

- hw_diag/utilities/hardware.py
**Issue**
- Link: #496 
- Summary:
**How**
**References**
**Checklist**
> Fix up all 0 serial check.

- hw_diag/utilities/hardware.py
**Issue**
- Link: #485 
- Summary: temp missing on rockpi
**How**
- adds correct sensor name on rockpi
**References**
Closes: #485
**Checklist**
> fix: temp missing on rockpi

- requirements.txt
- test-requirements.txt
grpcio has to be added externally to hm-pyhelper from 0.14.4+
**Checklist**
> Added newly required grpcio library dependency

- hw_diag/utilities/hardware.py
As per https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory the best way to calculate available and used memory is by using the "total" and "available" metrics.
Also see https://github.com/giampaolo/psutil/blob/master/scripts/meminfo.py
Related to #485 and #522
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: more accurate memory usage statistics

- hw_diag/diagnostics/ecc_diagnostic.py
- hw_diag/tests/diagnostics/test_ecc_diagnostic.py
**Issue**
ECCs at address 0x58 (found on some SyncroB.its) are expected to fail the `lockable` test and therefore require a workaround.
This PR modifies the ECC diagnostic result so that if (1) ECC is at 0x58 and (2) the _only_ failed test is the `lockable` one, the diagnostic result would still be successful.
- Link:
- Summary:
**How**
**References**
**Checklist**
> ECC diagnostics: Ignore lockable test failures in 0x58 ECCs

- hw_diag/diagnostics/bt_diagnostic.py
- hw_diag/tests/diagnostics/test_bt_diagnostic.py
- hw_diag/tests/test_hardware.py
- hw_diag/utilities/hardware.py
**Issue**
In the absence of a Bluetooth adapter, diagnostics (local dashboard, initFile.txt) will load after an unwelcome timeout. This happens because we attempt to fetch the BlueZ objects from DBus while the corresponding service is not registered on DBus.
This PR simply checks for the presence of the BlueZ service on DBus prior to fetching adapters, thus avoiding unnecessary timeouts.
- Link:
- Summary:
**How**
**References**
**Checklist**
> Don't fetch BlueZ objs unless service present

- .github/CODEOWNERS
- hw_diag/templates/helium_info.html
Show N/A (Not Required) for frequency on Nebra devices with missing frequency environment variable as this is no longer required and only used for manufacturing
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: add N/A to freq as no longer required

- hw_diag/templates/device_info.html
- hw_diag/tests/test_backup.py
- hw_diag/tests/test_crypto.py
- hw_diag/utilities/backup/__init__.py
- hw_diag/utilities/backup/base.py
- hw_diag/utilities/backup/myst.py
- hw_diag/utilities/backup/thingsix.py
- hw_diag/utilities/crypto.py
- hw_diag/utilities/db.py
- hw_diag/utilities/security.py
- hw_diag/views/backup_restore.py
- hw_diag/views/diagnostics.py
* a diaglog appears on the device info page
* the dialog disappears after click of the button but will come back every reload.
* only way to permanently disable the diaglog is to take a backup.
**[Issue](https://nebraltd.atlassian.net/browse/NEBD-238)**
- Link:
- Summary:
**How**
* a diaglog appears on the device info page
* the dialog disappears after click of the button but will come back every reload.
* only way to permanently disable the diaglog is to take a backup.
**References**
**Checklist**
> feat: show backup pending till such time the user takes a backup.

- hw_diag/templates/device_info.html
- add premium indicator to firmware version
- if on a commercial fleet, this changes the "claim on dashboard" link to "view device on dashboard" as it should already be connected to the dashboard in that case
Closes: #380 
Relates-to: #581
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add premium indicator to firmware version and change claim link

- hw_diag/templates/thix_set_region.html
- hw_diag/utilities/thix.py
- hw_diag/views/thingsix.py
Allow users to set region prior to ThingsIX onboard if not already set by gateway-rs.
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Allow users to set region.

- hw_diag/tests/test_get_serial_number.py
- hw_diag/utilities/hardware.py
- use /proc/device-tree/serial-number unless not available
- fall back to /proc/cpuinfo
- fixes serial number mismatch problem on bobcat
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> serial: change serial number check

- hw_diag/templates/helium_info.html
**Issue**
- Link:
- Summary:
**How**
Originally wasn't showing span on FREQ...
This PR fixes this.
**References**
**Checklist**
> fix span on button

- hw_diag/views/backup_restore.py
The backup and restore function is intended to back up the ThingsIX and Myst private keys.
As these are not present unless you are on premium firmware, we shouldn't leave backup and restore available as it just creates confusion
Closes #637
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Backup and restore commercial fleet only

- hw_diag/templates/device_info.html
- hw_diag/templates/helium_info.html
Change error message to "Awaiting Location Assertion" when not set
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Change error message when waiting for location assert

- hw_diag/utilities/backup/__init__.py
- hw_diag/utilities/backup/wingbits.py
- hw_diag/views/backup_restore.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add wingbits to backup
